# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 2.0.0.beta"
gem "hanami-router", "~> 2.0.0.beta"
gem "hanami-controller", "~> 2.0.0.beta"
gem "hanami-validations", "~> 2.0.0.beta"

gem "dry-types"
gem "puma"
gem "rake"

group :development, :test do
  gem "dotenv"
end

group :cli, :development, :test do
  gem "hanami-rspec"
end

group :test do
  gem "rack-test"
end

