version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
      - node_modules:/app/node_modules
    command: script/puma
    env_file: ".env"
    ports:
      - 2300:2300
    depends_on:
      - assets
    links:
      - assets
  assets:
    build:
      context: .
      dockerfile: Dockerfile-assets
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: "yarn start"
    env_file: ".env"
    working_dir: /app
    expose:
      - "8080"
volumes:
  bundle_path:
  node_modules:
