# frozen_string_literal: true

source "https://rubygems.org"

gem "rake"

gem "hanami-router", "~> 2.0.0.beta"
gem "hanami-controller", "~> 2.0.0.beta"
gem 'hanami-validations', git: 'https://github.com/hanami/validations', branch: 'main'
gem "hanami", "~> 2.0.0.beta"

gem "puma"

gem "redis-namespace"

group :cli, :development, :test do
  gem "dotenv"
  gem "hanami-rspec"
  gem "byebug"
end

group :test do
  gem "rack-test"
end
