# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 2.0.0.beta"
gem "hanami-router", "~> 2.0.0.beta"
gem "hanami-controller", "~> 2.0.0.beta"
gem "hanami-validations", "~> 2.0.0.beta"

gem "dry-effects"
gem "dry-matcher"
gem "dry-monads"
gem "dry-types"
gem "puma"
gem "rake"

gem "rom"
gem "rom-sql"
gem "pg"

group :development, :test do
  gem "dotenv"
  gem "faker"
  gem "rom-factory"
end

group :cli, :development, :test do
  gem "hanami-rspec"
end

group :test do
  gem "rack-test"
end
